apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-auth
  labels:
    app: camp-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camp-auth
  template:
    metadata:
      labels:
        app: camp-auth
    spec:
      containers:
        - name: camp-auth
          image: swr.af-south-1.myhuaweicloud.com/camp/service-c:image-tag  # Replace with the actual image name and tag
          ports:
            - containerPort: 50051 
          resources:
            requests:
              memory: "64Mi"    # Request 256Mi of memory
              cpu: "100m"        # Request 250 milliCPU
            limits:
              memory: "64Mi"    # Limit memory usage to 512Mi
              cpu: "100m" 
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          envFrom:
            - secretRef:
                name: auth-secret       # Limit CPU usage to 500 milliCPU
      imagePullSecrets:
        - name: default-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: camp-auth
  labels:
    app: camp-auth
spec:
  selector:
    app: camp-auth
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 31003    # NodePort (choose an available port in the range 30000-32767)
  type: NodePort  

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-name  
  annotations:
    cce.io/dew-resource: "[\"camp-auth-k8s-secret\"]" 
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dev-secrets-pclass 
spec:
  provider: cce
  parameters: 
    # Reference a secret in CSMS.
    objects: |
      - objectName: "camp-auth-k8s-secret"
        objectType: "csms"
        objectVersion: "latest"
        jmesPath:
          - path: grpcServerUrl
            objectAlias: grpcServerUrl
          - path: grpcServerPort
            objectAlias: grpcServerPort
          - path: datasource.url
            objectAlias: datasource.url
          - path: datasource.username
            objectAlias: datasource.username
          - path: datasource.password
            objectAlias: datasource.password
          - path: kafka.bootstrap-servers
            objectAlias: kafka.bootstrap-servers
          - path: redis.url
            objectAlias: redis.url
          - path:  terminal-secret
            objectAlias: terminal-secret
  secretObjects:                
    - secretName: auth-secret #name of the secret, spc will auto create this in your CCE
      type: Opaque
      data:
        - objectName: grpcServerUrl 
          key: grpcServerUrl  
        - objectName: grpcServerPort
          key: grpcServerPort
        - objectName: datasource.url
          key: datasource.url
        - objectName: datasource.username
          key: datasource.username  
        - objectName: datasource.password 
          key: datasource.password  
        - objectName: kafka.bootstrap-servers
          key: kafka.bootstrap-servers
        - objectName: redis.url
          key: redis.url
        - objectName: terminal-secret
          key: terminal-secret
