apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: swr.af-south-1.myhuaweicloud.com/ralf/service-b:image-tag  # Replace with the actual image name and tag
          ports:
            - containerPort: 3002
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector.observability.svc.cluster.local:4318/v1/traces"  # Adjust if using a centralized tracing server
          resources:
            requests:
              memory: "64Mi"    # Request 256Mi of memory
              cpu: "100m"        # Request 250 milliCPU
            limits:
              memory: "64Mi"    # Limit memory usage to 512Mi
              cpu: "100m"        # Limit CPU usage to 500 milliCPU
      imagePullSecrets:
        - name: default-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
